# Catppuccin Mocha — overwritten by matugen
$lock_text = rgba(cdd6f4ff)
$lock_subtext = rgba(bac2deff)
$lock_accent = rgba(89b4faff)
$lock_base = rgba(1e1e2eff)
$lock_check = rgba(a6e3a1ff)
$lock_fail = rgba(f38ba8ff)
$lock_capslock = rgba(f9e2afff)
